version: '2'
services:
  shopfront:
    image: celeduc/shopfront
    ports:
     - "8010:8010"
    links:
      - productcatalogue
      - stockmanager
  productcatalogue:
    image: celeduc/productcatalogue
    ports:
     - "8020:8020"
  stockmanager:
    image: celeduc/stockmanager
    ports:
     - "8030:8030"
